spring.application.name=altern
server.port=8081
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger
spring.datasource.url=jdbc:postgresql://localhost:5432/altern_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true