CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT users_username_unique UNIQUE (username),
    CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE IF NOT EXISTS problems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description VARCHAR(2000),
    difficulty VARCHAR(255),
    time_limit_ms INTEGER NOT NULL DEFAULT 5000,
    CONSTRAINT problems_difficulty_check CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD'))
);

CREATE TABLE IF NOT EXISTS test_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expected_output VARCHAR(255),
    input VARCHAR(255),
    hidden BOOLEAN NOT NULL DEFAULT FALSE,
    problem_id BIGINT,
    CONSTRAINT fk_test_cases_problem FOREIGN KEY (problem_id) REFERENCES problems(id)
);

CREATE TABLE IF NOT EXISTS submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language VARCHAR(255),
    problem_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    source_code VARCHAR(5000),
    status VARCHAR(255),
    created_at TIMESTAMP,
    passed_test_count INTEGER,
    total_test_count INTEGER,
    execution_time INTEGER,
    judged_at TIMESTAMP,
    memory_usage INTEGER,
    verdict_message VARCHAR(2000),
    CONSTRAINT fk_submissions_problem FOREIGN KEY (problem_id) REFERENCES problems(id),
    CONSTRAINT fk_submissions_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT submissions_language_check CHECK (language IN ('JAVA', 'PYTHON', 'CPP')),
    CONSTRAINT submissions_status_check CHECK (status IN (
        'PENDING',
        'ACCEPTED',
        'COMPILATION_ERROR',
        'TIME_LIMIT_EXCEEDED',
        'WRONG_ANSWER',
        'RUNTIME_ERROR'
    ))
);
