CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

ALTER TABLE users DROP CONSTRAINT IF EXISTS users_username_unique;
ALTER TABLE users ADD CONSTRAINT users_username_unique UNIQUE (username);
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN'));

INSERT INTO users (username, password_hash, role, created_at)
SELECT 'legacy_owner', '$2a$10$7EqJtq98hPqEX7fNZaFWoOeQ2E31x4n4t4DccnE9vrFica8FWHZcG', 'ADMIN', CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1
    FROM users
    WHERE username = 'legacy_owner'
);

ALTER TABLE problems ADD COLUMN IF NOT EXISTS time_limit_ms INTEGER;
UPDATE problems SET time_limit_ms = 5000 WHERE time_limit_ms IS NULL;
ALTER TABLE problems ALTER COLUMN time_limit_ms SET DEFAULT 5000;
ALTER TABLE problems ALTER COLUMN time_limit_ms SET NOT NULL;
ALTER TABLE problems DROP CONSTRAINT IF EXISTS problems_difficulty_check;
ALTER TABLE problems ADD CONSTRAINT problems_difficulty_check CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD'));

ALTER TABLE test_cases ADD COLUMN IF NOT EXISTS hidden BOOLEAN;
UPDATE test_cases SET hidden = FALSE WHERE hidden IS NULL;
ALTER TABLE test_cases ALTER COLUMN hidden SET DEFAULT FALSE;
ALTER TABLE test_cases ALTER COLUMN hidden SET NOT NULL;

ALTER TABLE submissions ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS judged_at TIMESTAMP;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS execution_time INTEGER;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS memory_usage INTEGER;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS verdict_message VARCHAR(2000);

UPDATE submissions
SET user_id = (
    SELECT id
    FROM users
    WHERE username = 'legacy_owner'
    FETCH FIRST 1 ROWS ONLY
)
WHERE user_id IS NULL;

ALTER TABLE submissions ALTER COLUMN problem_id SET NOT NULL;
ALTER TABLE submissions ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE submissions DROP CONSTRAINT IF EXISTS submissions_language_check;
ALTER TABLE submissions ADD CONSTRAINT submissions_language_check CHECK (language IN ('JAVA', 'PYTHON', 'CPP'));
ALTER TABLE submissions DROP CONSTRAINT IF EXISTS submissions_status_check;
ALTER TABLE submissions ADD CONSTRAINT submissions_status_check CHECK (status IN (
    'PENDING',
    'ACCEPTED',
    'COMPILATION_ERROR',
    'TIME_LIMIT_EXCEEDED',
    'WRONG_ANSWER',
    'RUNTIME_ERROR'
));
ALTER TABLE submissions DROP CONSTRAINT IF EXISTS fk_submissions_user;
ALTER TABLE submissions ADD CONSTRAINT fk_submissions_user FOREIGN KEY (user_id) REFERENCES users(id);
