ALTER TABLE problems ADD COLUMN IF NOT EXISTS input_format VARCHAR(2000);
ALTER TABLE problems ADD COLUMN IF NOT EXISTS output_format VARCHAR(2000);
ALTER TABLE problems ADD COLUMN IF NOT EXISTS starter_code_java VARCHAR(8000);
ALTER TABLE problems ADD COLUMN IF NOT EXISTS starter_code_python VARCHAR(8000);
ALTER TABLE problems ADD COLUMN IF NOT EXISTS starter_code_cpp VARCHAR(8000);
