CREATE TABLE IF NOT EXISTS problem_bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    problem_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_problem_bookmarks_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_problem_bookmarks_problem FOREIGN KEY (problem_id) REFERENCES problems(id),
    CONSTRAINT problem_bookmarks_user_problem_unique UNIQUE (user_id, problem_id)
);
